plugins:
  eslint:
    enabled: true
    channel: "eslint-7"
    config:
      extensions:
        - .ts
        - .js
  rubocop:
    enabled: true
    channel: "rubocop-0-89"
exclude_patterns:
  - "config/"
  - "db/"
  - "test/"
  - "**/node_modules/"
  - "**/vendor/"
