plugins:
  eslint:
    enabled: true
    channel: "eslint-7"
    config:
      extensions:
        - .ts
        - .js
exclude_patterns:
  - "*.config.js"
  - "app/javascript/channels/**"
  - "app/javascript/lib/dead/**"
  - "app/javascript/packs/application.js"
  - "config/"
  - "db/"
  - "test/"
  - "**/node_modules/"
  - "**/vendor/"
  - "**/*.d.ts"
