version: 2.1
orbs:
  ruby: circleci/ruby@1.1.1
  node: circleci/node@4.0.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
